# DataRoot University DS100 Test #2
На проходження тесту виділяється 87 хвилин.

## Python

### 1.  Реалізуйте функцію, яка повертає індекс кортежу, сума елементів якого є найбільшою серед кортежів в списку:
У відповідь вивести результат роботи ф-ції для наступного списку:
```
[(10, 20), (40), (30, 56, 25), (10, 20), (33), (40), (42), (10, 42), (42), (1,2,3), (4,5,6), (10,11,12), (7,8,9)]
```


```
```
```
```
```
```
```
Максимальна оцінка: 2 бали
Рекомендований час: 5хв
```

In [13]:
b = [(10, 20), (40), (30, 56, 25), (10, 20), (33), (40), (42), (10, 42), (42), (1,2,3), (4,5,6), (10,11,12), (7,8,9)]
def func(a):
    tmp_arr = []
    for i in a:
        sum=0
        if type(i)==tuple:
            for j in i:
                sum+=j
        else:
            sum=i
        tmp_arr.append(sum)
    max = 0
    index = None
    for i in range(len(tmp_arr)):
        if tmp_arr[i]>max:
            max=tmp_arr[i]
            index = i
    return 2
print (func(b))

2


### 2.  Реалізуйте функцію str -> dict, таку, що ключем dict є слово, а значенням - його кількість в початковій str:
У відповідь вивести результат роботи ф-ції для наступної строки:
```"Text mining, also referred to as text data mining, roughly equivalent to text analytics, is the process of deriving high-quality information from text. High-quality information is typically derived through the devising of patterns and trends through means such as statistical pattern learning. Text mining usually involves the process of structuring the input text (usually parsing, along with the addition of some derived linguistic features and the removal of others, and subsequent insertion into a database), deriving patterns within the structured data, and finally evaluation and interpretation of the output. 'High quality' in text mining usually refers to some combination of relevance, novelty, and interestingness."```

```
```
```
```
```
```
```
Максимальна оцінка: 2 бали
Рекомендований час: 5хв
```

In [26]:
strd = "Text mining, also referred to as text data mining, roughly equivalent to text analytics, is the process of deriving high-quality information from text. High-quality information is typically derived through the devising of patterns and trends through means such as statistical pattern learning. Text mining usually involves the process of structuring the input text (usually parsing, along with the addition of some derived linguistic features and the removal of others, and subsequent insertion into a database), deriving patterns within the structured data, and finally evaluation and interpretation of the output. 'High quality' in text mining usually refers to some combination of relevance, novelty, and interestingness."
def func(stro):   
    diction = {}
    ls = stro.split(' ')
    new_list = []
    for i in ls:
        strl = ''
        for j in range(len(i)):
            if i[j]!= ','and i[j]!= ' 'and i[j]!= '"' and i[j]!= "'" and i[j]!="."and i[j]!= "(" and i[j]!=")":
                strl = strl + i[j]
        new_list.append(strl)
    for i in new_list:
        if i  not in diction:
            diction[i] = 1
        elif i in diction:
            diction[i] += 1
    return diction
print(func(strd))

{'Text': 2, 'mining': 4, 'also': 1, 'referred': 1, 'to': 3, 'as': 2, 'text': 5, 'data': 2, 'roughly': 1, 'equivalent': 1, 'analytics': 1, 'is': 2, 'the': 8, 'process': 2, 'of': 7, 'deriving': 2, 'high-quality': 1, 'information': 2, 'from': 1, 'High-quality': 1, 'typically': 1, 'derived': 2, 'through': 2, 'devising': 1, 'patterns': 2, 'and': 6, 'trends': 1, 'means': 1, 'such': 1, 'statistical': 1, 'pattern': 1, 'learning': 1, 'usually': 3, 'involves': 1, 'structuring': 1, 'input': 1, 'parsing': 1, 'along': 1, 'with': 1, 'addition': 1, 'some': 2, 'linguistic': 1, 'features': 1, 'removal': 1, 'others': 1, 'subsequent': 1, 'insertion': 1, 'into': 1, 'a': 1, 'database': 1, 'within': 1, 'structured': 1, 'finally': 1, 'evaluation': 1, 'interpretation': 1, 'output': 1, 'High': 1, 'quality': 1, 'in': 1, 'refers': 1, 'combination': 1, 'relevance': 1, 'novelty': 1, 'interestingness': 1}


### 3. Спортсмен почав тренування, пробігши в перший день N км (N - ціле). Кожен наступний день він збільшував дистанцію пробігу на Р відсотків від дистанції пробігу попереднього дня(Р - дійсне, 0 < P < 50). По заданим Р, N, M, визначити, після якого дня сумарний пробіг спортсмена за всі дні буде вперше більшим, ніж M км (М - ціле, M > N). Вивести знайдену кількість днів К (K - ціле) і сумарний пробіг за К днів.

```
```
```
```
```
```
```
Максимальна оцінка: 3 бали
Рекомендований час: 7хв
```

In [27]:
def func(n,m,p,k=0):
    if n >=m:
        print(n,k)
    else:
        temp_distance = n+n*p/100.
        k+=1
        func(temp_distance,m,p,k)

### 4. Реалізуйте клас під назвою Triangle, побудований за трьома сторонами та містить два методи: обчислення площі та периметру.

```
```
```
```
```
```
```
Максимальна оцінка: 3 бали
Рекомендований час: 5хв
```

In [30]:
class Triangle():
    def __init__(self,a,b,c):
        self.a=a
        self.b=b
        self.c=c
    def perimeter(self):
        return self.a+self.b+self.c
    def square(self):
        per=self.perimeter()/2.
        return ((per-self.a)*(per-self.b)*(per-self.c))**(1./2.)


### 5.  Реалізуйте декоратор, який логує аргументи функцій та повернене значення кожного виклику. А при помилковому виклику відловлює та пише тип помилки. Необхідно виводити як позиційні(```*args```), так й іменовані аргументи(```**kwargs```):

Приклад застосування вашого декоратору в результаті:
```
>>> @log
... def func(*args):
...   return len(args) + sum(args)
>>> func(4, 4, 4)
You called func(4, 4, 4)
It returned 15
15

>>> func(4, 4, "4")
You called func(4, 4, "4")
It Raised TypeError
```

```
```
```
```
```
```
```
Максимальна оцінка: 4 бали
Рекомендований час: 15хв
```

## Libraries: numpy, scipy, pandas, matplotlib

### Numpy

### 6. Дана матриця:
\begin{align}
A = \begin{bmatrix}
    17 & 24 & 1 & 8 & 15 \\
    23 & 5 & 7 & 14 & 16 \\
    4 & 6 & 13 & 20 & 22 \\
    10 & 12 & 19 & 21 & 3 \\
    11 & 18 & 25 & 2 & 9 \\
\end{bmatrix}
\end{align}


#### Відніміть середнє арифметичне кожного рядку від кожного елементу у відповідному рядку:
```
```
```
```
```
```
```
Максимальна оцінка: 2 бали
Рекомендований час: 5хв
```

In [38]:
import numpy as np
A = np.array([np.array([17,24,1,8]),np.array([23,5,7,14,16]),np.array([4,6,13,20,22]),np.array([10,12,19,21,3]),np.array([11,18,25,2,9])])

for i in range(len(A)):
    A[i] = A[i]-A[i].mean()

print (A)


[array([  4.5,  11.5, -11.5,  -4.5]) array([ 10.,  -8.,  -6.,   1.,   3.])
 array([-9., -7.,  0.,  7.,  9.]) array([ -3.,  -1.,   6.,   8., -10.])
 array([ -2.,   5.,  12., -11.,  -4.])]


# 7. Дано наступні матриці:
\begin{align}
A = \begin{bmatrix}
    1 & 24 & 1 & 8 & 15 \\
    -3 & 5 & 7 & -14 & 16 \\
    4 & 6 & -3 & 20 & 2 \\
    10 & 12 & 19 & 21 & 3 \\
    1 & 1 & 2 & -2 & 0 \\
\end{bmatrix}
\end{align}
\begin{align}
\end{align}
\begin{align}
B = \begin{bmatrix}
    17 & 24 & 1 & 8 & 15 \\
    23 & 5 & 7 & 14 & 16 \\
    4 & 6 & 13 & 20 & 22 \\
    10 & 12 & 19 & 21 & 3 \\
    11 & 18 & 25 & 2 & 9 \\
\end{bmatrix}
\end{align}
Знайти:

#### 7.1. $(A B)^{-1}B$

```
```
```
```
```
```
```
Максимальна оцінка: 1 бал
Рекомендований час: 2хв
```

In [39]:
import numpy as np
A = np.array([np.array([1,24,1,8,15]),np.array([-3,5,7,-14,16]),np.array([4,6,-3,20,2]),np.array([10,12,19,21,3]),np.array([1,1,2,-2,0])])
B = np.array([np.array([17,24,1,8,15]),np.array([23,5,7,-14,16]),np.array([4,6,13,20,22]),np.array([10,12,19,21,3]),np.array([11,18,25,2,9])])
C=np.dot(A,B)
Cinv = np.linalg.inv(C)
res= np.dot(C,B)
print (res)

[[33890 35586 26057 12350 41014]
 [ 6890  7835  7445   600 11385]
 [22620 21294 18913 13580 24446]
 [49565 51018 51691 29559 50792]
 [ 1530  1879  1668  -124  1201]]


#### 7.2. Детермінант: $\det ((A B)^{-1}B)$

```
```
```
```
```
```
```
Максимальна оцінка: 1 бал
Рекомендований час: 2хв
```

In [41]:
import numpy as np
A = np.array([np.array([1,24,1,8,15]),np.array([-3,5,7,-14,16]),np.array([4,6,-3,20,2]),np.array([10,12,19,21,3]),np.array([1,1,2,-2,0])])
B = np.array([np.array([17,24,1,8,15]),np.array([23,5,7,-14,16]),np.array([4,6,13,20,22]),np.array([10,12,19,21,3]),np.array([11,18,25,2,9])])
C=np.dot(A,B)
Cinv = np.linalg.inv(C)
res= np.dot(C,B)
determinant = np.linalg.det(res)
print (determinant)

-3.83400256287e+18


#### 7.3. Нормалізуйте: $(A B)^{-1}B$
```
```
```
```
```
```
```
Максимальна оцінка: 1 бал
Рекомендований час: 2хв
```

In [42]:
import numpy as np
A = np.array([np.array([1,24,1,8,15]),np.array([-3,5,7,-14,16]),np.array([4,6,-3,20,2]),np.array([10,12,19,21,3]),np.array([1,1,2,-2,0])])
B = np.array([np.array([17,24,1,8,15]),np.array([23,5,7,-14,16]),np.array([4,6,13,20,22]),np.array([10,12,19,21,3]),np.array([11,18,25,2,9])])
C=np.dot(A,B)
Cinv = np.linalg.inv(C)
res= np.dot(C,B)
norma = np.linalg.norm(res)
print (norma)

136098.424142


#### 7.4. Змініть матрицю B таким чином, щоб всі елементи k, такі що 3 < k < 16, змінили знак.
```
```
```
```
```
```
```
Максимальна оцінка: 3 бали
Рекомендований час: 5хв
```

In [44]:
B = np.array([np.array([17,24,1,8,15]),np.array([23,5,7,-14,16]),np.array([4,6,13,20,22]),np.array([10,12,19,21,3]),np.array([11,18,25,2,9])])
for i in range(len(B)):
    for j in range(len(B[i])):
        if B[i][j] >3 and B[i][j]<16:
            B[i][j]*=-1
print (B)

[[ 17  24   1  -8 -15]
 [ 23  -5  -7 -14  16]
 [ -4  -6 -13  20  22]
 [-10 -12  19  21   3]
 [-11  18  25   2  -9]]


### Pandas

### 8. Розглянемо наступний словник ```data``` та список ```labels```:

In [1]:
import numpy as np

data = {'animal': ['cat', 'cat', 'snake', 'dog', 'dog', 'cat', 'snake', 'cat', 'dog', 'dog'],
        'age': [2.5, 3, 0.5, np.nan, 5, 2, 4.5, np.nan, 7, 3],
        'visits': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'priority': ['yes', 'yes', 'no', 'yes', 'no', 'no', 'no', 'yes', 'no', 'no']}

labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

#### 8.1. Створіть ```DataFrame``` ```df``` з даних словника ```data``` з індексами зі списку ```labels```:
```
```
```
```
```
```
```
Максимальна оцінка: 1 бал
Рекомендований час: 1хв
```

In [48]:
import pandas as pd

data = {'animal': ['cat', 'cat', 'snake', 'dog', 'dog', 'cat', 'snake', 'cat', 'dog', 'dog'],
        'age': [2.5, 3, 0.5, np.nan, 5, 2, 4.5, np.nan, 7, 3],
        'visits': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'priority': ['yes', 'yes', 'no', 'yes', 'no', 'no', 'no', 'yes', 'no', 'no']}

labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

df = pd.DataFrame(data,index=labels)

   age animal priority  visits
a  2.5    cat      yes       1
b  3.0    cat      yes       3
c  0.5  snake       no       2
d  NaN    dog      yes       3
e  5.0    dog       no       2
f  2.0    cat       no       3
g  4.5  snake       no       1
h  NaN    cat      yes       1
i  7.0    dog       no       2
j  3.0    dog       no       1


#### 8.2. Відобрзіть базову інформацію про цей ```DataFrame``` та його дані:
```
```
```
```
```
```
```
Максимальна оцінка: 1 бал
Рекомендований час: 1хв
```

In [51]:
import pandas as pd

data = {'animal': ['cat', 'cat', 'snake', 'dog', 'dog', 'cat', 'snake', 'cat', 'dog', 'dog'],
        'age': [2.5, 3, 0.5, np.nan, 5, 2, 4.5, np.nan, 7, 3],
        'visits': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'priority': ['yes', 'yes', 'no', 'yes', 'no', 'no', 'no', 'yes', 'no', 'no']}

labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

df = pd.DataFrame(data,index=labels)
print(df.info())

<class 'pandas.core.frame.DataFrame'>
Index: 10 entries, a to j
Data columns (total 4 columns):
age         8 non-null float64
animal      10 non-null object
priority    10 non-null object
visits      10 non-null int64
dtypes: float64(1), int64(1), object(2)
memory usage: 280.0+ bytes
None


#### 8.3. Поверніть перші 3 рядки ```DataFrame``` ```df```:
```
```
```
```
```
```
```
Максимальна оцінка: 1 бал
Рекомендований час: 1хв
```

In [52]:
import pandas as pd

data = {'animal': ['cat', 'cat', 'snake', 'dog', 'dog', 'cat', 'snake', 'cat', 'dog', 'dog'],
        'age': [2.5, 3, 0.5, np.nan, 5, 2, 4.5, np.nan, 7, 3],
        'visits': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'priority': ['yes', 'yes', 'no', 'yes', 'no', 'no', 'no', 'yes', 'no', 'no']}

labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

df = pd.DataFrame(data,index=labels)
df.head(3)

age animal priority  visits
a  2.5    cat      yes       1
b  3.0    cat      yes       3
c  0.5  snake       no       2

#### 8.4. Виберіть стовпчики ```"animal"``` та ```"age"``` з ```DataFrame``` ```df```:
```
```
```
```
```
```
```
Максимальна оцінка: 1 бал
Рекомендований час: 1хв
```

In [53]:
import pandas as pd

data = {'animal': ['cat', 'cat', 'snake', 'dog', 'dog', 'cat', 'snake', 'cat', 'dog', 'dog'],
        'age': [2.5, 3, 0.5, np.nan, 5, 2, 4.5, np.nan, 7, 3],
        'visits': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'priority': ['yes', 'yes', 'no', 'yes', 'no', 'no', 'no', 'yes', 'no', 'no']}

labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

df = pd.DataFrame(data,index=labels)
df[["animal","age"]]

animal  age
a    cat  2.5
b    cat  3.0
c  snake  0.5
d    dog  NaN
e    dog  5.0
f    cat  2.0
g  snake  4.5
h    cat  NaN
i    dog  7.0
j    dog  3.0

#### 8.5 Виберіть дані з рядків ```[3, 4, 8]``` та стовпчиків ```['animal', 'age']```:
```
```
```
```
```
```
```
Максимальна оцінка: 1 бал
Рекомендований час: 1хв
```

In [60]:
import pandas as pd

data = {'animal': ['cat', 'cat', 'snake', 'dog', 'dog', 'cat', 'snake', 'cat', 'dog', 'dog'],
        'age': [2.5, 3, 0.5, np.nan, 5, 2, 4.5, np.nan, 7, 3],
        'visits': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'priority': ['yes', 'yes', 'no', 'yes', 'no', 'no', 'no', 'yes', 'no', 'no']}

labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

df = pd.DataFrame(data,index=labels)

df.loc[['d','e','i'],["animal","age"]]

animal  age
d    dog  NaN
e    dog  5.0
i    dog  7.0

#### 8.6. Виберіть лише ті рядки, в яких к-сть візитів більша ніж 3:
```
```
```
```
```
```
```
Максимальна оцінка: 1 бал
Рекомендований час: 1хв
```

In [61]:
import pandas as pd

data = {'animal': ['cat', 'cat', 'snake', 'dog', 'dog', 'cat', 'snake', 'cat', 'dog', 'dog'],
        'age': [2.5, 3, 0.5, np.nan, 5, 2, 4.5, np.nan, 7, 3],
        'visits': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'priority': ['yes', 'yes', 'no', 'yes', 'no', 'no', 'no', 'yes', 'no', 'no']}

labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

df = pd.DataFrame(data,index=labels)
df[df.visits>3]

Empty DataFrame
Columns: [age, animal, priority, visits]
Index: []

#### 8.7. Виберіть рядки, де вік відсутній, тобто ```NaN```:
```
```
```
```
```
```
```
Максимальна оцінка: 1 бал
Рекомендований час: 1хв
```

Empty DataFrame
Columns: [age, animal, priority, visits]
Index: []

#### 8.8. Виберіть рядки з котами, вік яких більше ніж 2:
```
```
```
```
```
```
```
Максимальна оцінка: 1 бал
Рекомендований час: 1хв
```

In [71]:
import pandas as pd

data = {'animal': ['cat', 'cat', 'snake', 'dog', 'dog', 'cat', 'snake', 'cat', 'dog', 'dog'],
        'age': [2.5, 3, 0.5, np.nan, 5, 2, 4.5, np.nan, 7, 3],
        'visits': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'priority': ['yes', 'yes', 'no', 'yes', 'no', 'no', 'no', 'yes', 'no', 'no']}

labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

df = pd.DataFrame(data,index=labels)
df[(df.animal=='cat') & (df.age>2)]

age animal priority  visits
a  2.5    cat      yes       1
b  3.0    cat      yes       3

#### 8.9. Підрахуйте середній вік для кожного з типів тварин:
```
```
```
```
```
```
```
Максимальна оцінка: 2 бали
Рекомендований час: 2хв
```

#### 8.10. Відсортуйте ```df``` по-перше за віком в спадаючому порядку, по-друге за к-стю візитів в зростаючому порядку:
```
```
```
```
```
```
```
Максимальна оцінка: 2 бали
Рекомендований час: 2хв
```

#### 8.11. Стовпець "priority" містить значення "yes" та "no". Замінити цей стовпець стовпчиком булевих значень: "yes" на True, а "no" на False:
```
```
```
```
```
```
```
Максимальна оцінка: 2 бали
Рекомендований час: 2хв
```

## Scipy & Matplotlib

### 9. За допомогою scipy згенерувати та за допомогою matplotlib побудувати функцію розподілу ймовірностей для вибірок, правильно підписавши осі та назвавши графік з обраними відповідними параметрами:

#### 9.1. Для виібрки з нормально розподіленої випадкової величини:
```
```
```
```
```
```
```
Максимальна оцінка: 3 бали
Рекомендований час: 5хв
```

In [79]:
import scipy.stats as st
import numpy as np
from matplotlib.pylab import plt
norm = st.norm(loc=5, scale=2)

#### 9.2. Для вибірки з розподілу Бернулі:
```
```
```
```
```
```
```
Максимальна оцінка: 3 бали
Рекомендований час: 5хв
```

#### 9.3. Для вибірки з біноміального розподілу:
```
```
```
```
```
```
```
Максимальна оцінка: 3 бали
Рекомендований час: 5хв
```

#### 9.4. Для вибірки з розподілу Пуассона:
```
```
```
```
```
```
```
Максимальна оцінка: 3 бали
Рекомендований час: 5хв
```